CUISINES: list[str] = [
    # Singapore's four main culinary traditions
    "Chinese",
    "Malay",
    "Indian",
    "Western",
    # Chinese regional styles common in Singapore
    "Hokkien",
    "Cantonese",
    "Teochew",
    "Hakka",
    "Chinese Muslim",
    "Peranakan",
    # Southeast Asian
    "Indonesian",
    "Thai",
    "Vietnamese",
    "Filipino",
    "Burmese",
    "Khmer",
    "Singaporean",
    # East Asian
    "Japanese",
    "Korean",
    "Taiwanese",
    "Mongolian",
    # South Asian
    "Pakistani",
    "Bangladeshi",
    "Sri Lankan",
    "Nepalese",
    "Tibetan",
    # Middle Eastern
    "Middle Eastern",
    "Lebanese",
    "Turkish",
    "Persian",
    "Arabian",
    # European
    "Italian",
    "French",
    "Spanish",
    "British",
    "German",
    "Greek",
    "Mediterranean",
    "Eastern European",
    "Russian",
    # Americas
    "American",
    "Mexican",
    "Brazilian",
    "Argentine",
    "Peruvian",
    "Canadian",
    # Other
    "International",
    "Fusion",
    "Australian",
    "Seafood",
    "Steamboat",
    "Hotpot",
    "Buffet",
    "Cafe",
    "Kopitiam",
    "Bakery",
    "Dessert",
    "Hawker",
    "Street Food",
    "Noodles",
    "Rice",
    "Dim Sum",
    "Pizza",
    "Sushi",
    "Ramen",
    "Burger",
    "Sandwich",
    "Salad",
    "Soup",
    "Grill",
    "BBQ",
    "Vegan",
    "Vegetarian",
    "Halal",
    "Healthy",
    "Fast Food",
    "Food Court",
    "Bar",
]

MAX_CUISINES_PER_PLACE = 5

CUISINES_LOOKUP: dict[str, str] = {name.lower(): name for name in CUISINES}
